### ISSUE TITLE
The sign numbers of 4th and 10th house are displayed too high, appearing in 1st house 

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#10]
The sign numbers in Maitreya 8 are displayed in wrong place using north indian view. The sign numbers of the 4th and 10th house are displayed too high, appearing in the bottom of the 1st house in case where the window is in rectangular shape, like in astakavarga view, or main view with main window stretched to rectangular format.

![image](https://cloud.githubusercontent.com/assets/24913267/23215622/b9db8d44-f91b-11e6-9328-ad756573686d.png)

![image](https://cloud.githubusercontent.com/assets/24913267/23215767/2d00e2c4-f91c-11e6-88ea-62a860200776.png)

**Comment by martin-pe** [comment]
should be okay now, see screen shot. Sign names or symbols are aligned around the rectangle of the center text.
![screenshot at 2017-03-04 13 33 25](https://cloud.githubusercontent.com/assets/13454741/23578813/9e702e0e-00df-11e7-9b4c-98f3af24e1f1.png)
