### ISSUE TITLE
Bug: Editing birth data does not update the chart (in beta3)

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#11]
Editing birth data does not reflect in chart (in beta3), at least when using multiple views. Workaround: One has to save the chart, close, and reopen to get the grapics updated.

I have tested this only using multiple views, not using the standard view.

**Comment by martin-pe** [comment]
I tested it and did not find any error.
What is your OS?
What is you config? Single or multiple view (which)? Did you open a chart or create a new one?
Do you have an example?

**Comment by ossiviljakainen** [comment]
Thanks, 

Just noticed that adjusting the date or time or both are reflected in the planets table, but the chart itself remains with aries lagna. My OS info below. Maitreya version displayed in the screenshot. My config relevant to this is Multiple views, North Indian chart. Config file attached.
[config.json.zip](https://github.com/martin-pe/maitreya8/files/857139/config.json.zip)


**OS version**
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Maitreya version**
![image](https://cloud.githubusercontent.com/assets/24913267/24133120/1fa3a0ac-0e03-11e7-89ab-b59958dfced2.png)

Screenshot demonstrating the chart update bug. Please note that the planets table display the correct values, but the chart displays as aries as lagna, while the table displays sagittarius.
![image](https://cloud.githubusercontent.com/assets/24913267/24133054/ca4ebd8a-0e02-11e7-982c-6556492255e1.png)

**Comment by martin-pe** [comment]
found the bug, should work now
