### ISSUE TITLE
Bug: Lagna always remains Aries in Partner View

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#12]
In Partner View, the lagna remains always Aries when using North Indian chart format.

Same goes for Synastry:
![image](https://cloud.githubusercontent.com/assets/24913267/24313511/c12a68b8-10e5-11e7-9203-403347865353.png)

for Composite Chart:
![image](https://cloud.githubusercontent.com/assets/24913267/24313465/8f6b6d4a-10e5-11e7-906e-458df35f1643.png)

And all the vargas:
![image](https://cloud.githubusercontent.com/assets/24913267/24313536/df97f518-10e5-11e7-9111-bdb1d1b4e8b6.png)

**Comment by martin-pe** [comment]
should be fixed now. please verify.

**Comment by mack3457** [comment]
Verified as fixed.
