### ISSUE TITLE
Typos in german translation

### ISSUE THREAD

**Issue by mack3457** [martin-pe/maitreya8#14]
When changing the location and switching to e.g. "ephemeris", I get a dialog stating:

"Die Honfiguration wurde geändert. [...]"

It must be "Konfiguration" - use a capital K instead of H.

**Comment by mack3457** [comment]
Another typo: again on the configuration page -> Ephemeride (ephemeris) -> Berechnung (calculation) -> Geozentisch (geocentric)
Geozentisch is missing an 'r': Geozentrisch would be correct

**Comment by mack3457** [comment]
Again: in Konfiguration -> Benutzerschnittstelle -> Planeten und Zeichen -> "Darstellung der Positioen" must be "... Positionen".

**Comment by martin-pe** [comment]
fixed an will appear in stable release
