### ISSUE TITLE
Uncommon abbreviation for Tula

### ISSUE THREAD

**Issue by mack3457** [martin-pe/maitreya8#15]
Tula is abbreviated as "Thu", which is rather confusing, as the word is तूला originally and the letter त is normally transliterated as 'ta' and not 'tha', which on the other hand is the transliteration for the letter थ ,

So better abbreviate Tula as Tul or similar.

**Comment by mack3457** [comment]
This is also true for the complete word Thula / Tula. As थ is pronounced as a 't' followed by an 'h' and त as a 't' NOT followed by an 'h', Tula should not be written as Thula, as this implies a different starting letter and therefore a different word.

**Comment by martin-pe** [comment]
fixed
