### ISSUE TITLE
Lagna in north indian style not updated on changed birth date

### ISSUE THREAD

**Issue by mack3457** [martin-pe/maitreya8#16]
When using "Vedic Comprehensive" chart style in north indian style and changing the birth date, the lagna doesn't get updated on D-1 and D-9.

Lagna in the list of all planet's positions gets updated correctly.

When opening a separate D1- or similar chart, the lagna is correct. Same, when saving and loading the chart again.

**Comment by mack3457** [comment]
Seems to be the problem #11 .

**Comment by martin-pe** [comment]
Should be fixed, please verify

**Comment by mack3457** [comment]
Yes, works fine now.
