### ISSUE TITLE
Building debug version

### ISSUE THREAD

**Issue by GauthamBanasandra** [martin-pe/maitreya8#19]
Hi,

Is it possible to build a debug version of this repo?

Thanks,
--Gautham

**Comment by martin-pe** [comment]
Hi Gautham,

What is your OS?
Linux/UNIX version (Mac as well) is build with -g debug option (gcc). Unter Windows the executable is stripped during the release build. You can compile by hand to keep debug info.

Best
Martin

**Comment by GauthamBanasandra** [comment]
I'm using Ubuntu. There seems to be a Makefile in each of the src directories. Could you please tell in which of these Makefile and at which line I'm supposed to put the -g option?

**Comment by martin-pe** [comment]
Please try under bash "export CFLAGS='-g'" and same for CPPFLAGS. Then configure and make.
There is a command line interface unter src/jyotish called maitreya8t.
