### ISSUE TITLE
Bug: crash in parner view / Uranian tab

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#2]
Maitreya 8 alpha crashes in parner view when clicking on Uranian tab

**Comment by martin-pe** [comment]
Issue should be fixed in current version

**Comment by ossiviljakainen** [comment]
Going to Partner View / Uranian tab no longer causes maitreya to crash,  but now freezes the program eating 100% of CPU.

![image](https://cloud.githubusercontent.com/assets/24913267/24133617/efecaa08-0e06-11e7-8ce3-74a8f34368cf.png)

I also have some yogas I have added in yoga editor that give error message upon opening of a chart, and I have not taken the time to fix them. Just got the intuition that this might be related.

![image](https://cloud.githubusercontent.com/assets/24913267/24133669/4b5ff778-0e07-11e7-9a86-0998cbcb3a67.png)

![image](https://cloud.githubusercontent.com/assets/24913267/24133680/671f9478-0e07-11e7-9d64-a7d5a87a49b9.png)

**Comment by ossiviljakainen** [comment]
It still causes the program to crash.
