### ISSUE TITLE
Timezone settings

### ISSUE THREAD

**Issue by kpmore** [martin-pe/maitreya8#20]
Please check the timezone settings , as i installed 8.0 released (June 24 2017)  and created new chart , i had to manually change the DST settings to 00:00 for Indian cities, whereas it was no so in previous versions.

**Comment by martin-pe** [comment]
Discussion about DST is a long story and has currently no good solution.
Birth data dialog in Maitreya always uses the operating system settings of DST!
This is often correct but not always, i.e. may be wrong if birth location differs in dst.
Windows and Linux/Unix/Mac implementations of time zones and DST are unfortunately incompatible. So it is very hard to make the software aware of the timezone and DST connected to a location.

**Comment by Translator5** [comment]
May you rename the option "Timezone" to "Timezone Summand", as for me right now putting in UTZ +6 / MEZ +5 result in +7/+6 as I live in West-Europe with UTZ +1.
Whyever your program adds the timezone instead of replacing it - may also its just the German translation, that says just "Timezone". :)

**Comment by ossiviljakainen** [comment]
> I really do not understand the timezone option. Is it using MEZ / UTZ or something else ? If UTZ, why I have to add 2h to get to timezone 6+, if my current timezone is UTC = +1. What kind of Magic is this? And how to rellocate?

In timezone field, you have to input the timezone where the birth took place. Suppose the native was born in Paris. In Time Zone field, you have to enter 01:00. Same will get automatically filled in if you perform "Search Location" for "Paris" and choose "Paris Ile-de-France".

If your current timezone is Central European Time, CET (GMT+1) and the desired location is the same timezone (GMT+1), then you don't need to alter anything.

![Image](https://github.com/user-attachments/assets/8073aff0-c59f-452d-9fb5-693fdc905750)

Check your computer's timezone settings. And check in Maitreya settings that your Standard Location is set correctly.
