### ISSUE TITLE
Name is not updated in print-header

### ISSUE THREAD

**Issue by zensubz** [martin-pe/maitreya8#21]
Hi,
Thank you for making this great software. I have noted one small issue - a cosmetic one - during printing a chart in Vedic-Comprehensive mode. The header doesn't seem to get replaced with the new name (despite the fact that I have saved the chart with the new name). In all pages (2 & 3) it appears as nn/Date.../Time..., while it would be better if 'nn' is replaced with the corresponding chart's name...

**Comment by martin-pe** [comment]
Header and footer of printout do not have the context of the printed chart, this is really a bug.
It is already fixed, I'll commit the changes and include the fix in the next release.
Thanks for reporting!
