### ISSUE TITLE
Bug: Arudha Lagna calculation sometimes wrong

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#34]
In this chart, Sag is displayed as AL. Lagna lord is in 10th, and 10th from 10th is Pisces.

![image](https://user-images.githubusercontent.com/24913267/32699284-928b677c-c7bb-11e7-8103-7bfee40481bb.png)

**Comment by martin-pe** [comment]
This would be Raman's way to calculate. You can do so if you configure VedicCalculation->Jaimini->Arudha Mode -> Raman.
In Parasara mode the first and seventh cannot be Arudha, see BPHS 29,4-5:
    The same Bhava, or the 7th from it does not become its Pad. When the Pad falls in the same Bhava, the 10th therefrom be treated, as its Pad. Similarly, when the 7th becomes the Pad of a Bhava, the 4th from the original Bhava in question be treated, as its Pad.
