### ISSUE TITLE
Bug: The "New view" item is missing from the right-click context menu

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#4]
"New item" visible in Maitreya 7:
![image](https://cloud.githubusercontent.com/assets/24913267/21639146/3a9d89da-d277-11e6-8755-c1d61a717cb9.png)

"New item" gone from Maitreya 8:
![image 1](https://cloud.githubusercontent.com/assets/24913267/21639154/41b97080-d277-11e6-991e-9345acae99d8.png)

**Comment by martin-pe** [comment]
the items were completely unsorted :)
I rearranged them in a way that may be more logical and more intuitive
- title
- items for the whole horoscope (new view, edit data, animate) if available
- items for the current view, e.g. skin or object selection

![screenshot at 2017-01-07 09 58 17](https://cloud.githubusercontent.com/assets/13454741/21740658/8b480860-d4c0-11e6-8b61-e9a6a669b199.png)
