### ISSUE TITLE
Bug: Editing birth data does not reflect the Rasi or Navamsa chart

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#5]
Editing birth data or using the new up/down arrows and hitting OK does not reflect in Rasi or Navamsa. Only the degrees in the planets table change, but no change in graphical chart. Workaround: One has to save the chart, close, and reopen to get the grapics updated.

I have tested this only using multiple views, not using the standard view.

**Comment by martin-pe** [comment]
fixed. Update on chart grid in multiple view was missing.
