### ISSUE TITLE
Trouble installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by heems** [martin-pe/maitreya8#57]
Hi! 

I tried installing the Maitreya 8 deb on 20.04 LTS but got this dependency error:
``
The following packages have unmet dependencies:
 maitreya8 : Depends: libwxgtk3.0-0v5 (>= 3.0.2+dfsg) but it is not installable
``

I tried to solve the issue by installing libwxgtk3.0 from here: https://answers.launchpad.net/ubuntu/focal/amd64/libwxgtk3.0-0v5/3.0.4+dfsg-12

which seemed like the proper replacement.

Maitreya then installed successfully. But when I try to run it it crashes with this error:
``
(maitreya8.bin:13429): Gtk-ERROR **: 14:35:39.391: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)
``

Any advice for how to get this working?

Thanks.

**Comment by erdoukki** [comment]
Same problem/issue for me

**Comment by martin-pe** [comment]
See download page with new Debian package and build instructions.
