### ISSUE TITLE
Bug: Incomplete usage syntax given in textclient help msg

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#6]
The help message of maitreya8t gives incomplete info for syntax:

Current:
`Usage: maitreya8t [--help] [--help] [--date <str>] [--location <str>] `

Should be updated to:
`Usage: maitreya8t [--help] [--help] [--date="<str>"] [--location="<str>"] `

Current:
```
  --date=<str>              	Set UT date YYYY-MM-DD HH:MM:SS
  --location=<str>          	Set location "name LL:LL BB:BB ZZ"
```

Should be updated to:
```
  --date=<str>              	Set UT date "YYYY-MM-DD HH:MM:SS"
  --location=<str>          	Set location "name LL:LL BB:BB (+/-)ZZ"
```

Also the first line appears twice:  
```
  --help                    	show this help message
  --help                    	show this help message
```

**Comment by martin-pe** [comment]
Should be okay now.
Moreover plain html export and shadbala added

**Comment by ossiviljakainen** [comment]
Still some required quotation marks are missing from the help text:

Current:
`Usage: maitreya8t [--help] [--date <str>] [--location <str>]`

Should be updated to:
`Usage: maitreya8t [--help] [--date="<str>"] [--location="<str>"]`


Current:
`  --date=<str>              	Set UT date YYYY-MM-DD HH:MM:SS`

Should be updated to:
`  --date=<str>              	Set UT date "YYYY-MM-DD HH:MM:SS"`

The file=<str> does not require quotation marks, as one can use the unix syntax using the backslash as delimiter for space character, or alternatively encolose the filename in quotation marks.

**Comment by mack3457** [comment]
I disagree on the quotes in the usage line: a string as a parameter will always have to obey the rules of parameter strings on your particular operating system.

If you write --date=2017-01-01\ 18:57:23 on unix or --date=2017-01-0"1 "18:57:23 on windows or unix or use single quotes on unix or enclose the complete argument in quotes, doesn't make any difference.

Using --date=<str> vs. --date <str> etc.: yes, you are right, the normal default would be to use the equal sign on long options and no equal sign on the short form of the option if available. So, in the usage line, it should read --date=<str> etc., even if --date <str> can be used as well.

**Comment by ossiviljakainen** [comment]
Ok thanks :)
