### ISSUE TITLE
Astakavarga displays always aries as lagna, regardless of actual lagna

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#9]
In astakavarga view using north indian chart the lagna appears always to be aries, regardless of actual lagna of the particluar chart.

Maitreya 8.0.beta2 displays it wrong:
![image](https://cloud.githubusercontent.com/assets/24913267/23215316/9bbde114-f91a-11e6-92b2-dc0f922f8e2d.png)

Maitreya 7.0.3 displays it correctly:
![image](https://cloud.githubusercontent.com/assets/24913267/23215536/6f35d57e-f91b-11e6-8828-93906d5023cd.png)

**Comment by martin-pe** [comment]
Should be okay now
